# https://github.com/puckel/docker-airflow/blob/master/docker-compose-LocalExecutor.yml
version: '2.1'
services:

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - airflow-volume:/var/lib/postgresql/data
        ports:
          - "5432:5432"

    airflow-webserver:
        build: ./airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./airflow/plugins:/usr/local/airflow/plugins
            - ./airflow/utils:/usr/local/airflow/utils
        ports:
            - "8080:8080"
        command: webserver

    api:
        build: ./api
        volumes:
          - ./api:/app
        ports:
          - "3000:3000"

volumes:
  airflow-volume:
