# https://github.com/puckel/docker-airflow/blob/master/docker-compose-LocalExecutor.yml
version: '2.1'
services:

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - airflow-volume:/var/lib/postgresql/data
        ports:
          - "5432:5432"

    airflow-webserver:
        build: ./airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - SLACK_OAUTH_TOKEN=${SLACK_OAUTH_TOKEN}
            - TASK_DEF=${TASK_DEF}
            - TASK_SUBNET=${TASK_SUBNET}
            - FARGATE_CLUSTER=${FARGATE_CLUSTER}
            - S3_BUCKET=${S3_BUCKET}
            - AIRFLOW__CORE__DAG_CONCURRENCY=50
            - AIRFLOW__CORE__PARALLELISM=50
            - AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW=graph
            # - AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL=20
            - AIRFLOW__OPERATORS__DEFAULT_RAM=10
            - AIRFLOW__OPERATORS__DEFAULT_DISK=10
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./airflow/plugins:/usr/local/airflow/plugins
            - ./airflow/utils:/usr/local/airflow/utils
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.kubernetes/config:/usr/local/airflow/.kube/config
        ports:
            - "8080:8080"
        command: webserver

    api:
        build: ./api
        volumes:
          - ./api:/app
        ports:
          - "3000:3000"

volumes:
  airflow-volume:
