FROM puckel/docker-airflow:1.10.4
RUN pip install slackclient==2.0.0 --user
RUN pip install boto3==1.10.25 --user
RUN pip install websocket-client==0.56.0 --user
RUN pip install docker==4.1.0 --user
RUN pip install kubernetes==10.0.1 --user
